name: Build and Test

on:
  push:
    branches: 
      - "*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
    - name: Run tests
      run: cargo test --release
  build:
    runs-on: ubuntu-latest
    env:
      RUST_CFLAGS: "-C link-args=-s"
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            target: wasm32-unknown-unknown
      - name: Run Build
        run: cargo wasm

